#!/usr/bin/env bash
#
# Copy the canonical FERAL design tokens into the desktop app.
#
#   source of truth : feral-client-v2/src/styles/tokens.css
#   generated copy  : desktop/src/tokens.css
#
# WHY A BUILD STEP AND NOT A HAND-MAINTAINED COPY: the desktop app is a
# separate Vite build with its own package.json, so it cannot import across
# the package boundary. The two remaining options were a hand-copied block
# with a "keep these in sync" comment, or this. A comment is a request that
# a human remember; this is a step that runs. `npm run build` (and therefore
# `tauri build`, whose beforeBuildCommand is `npm run build && npm run
# stage:bundle`) re-copies before every bundle, so a token edit in v2 cannot
# ship to the desktop app stale. Same reasoning as stage_bundle.sh reading
# .python-pin instead of restating the version.
#
# The generated file IS committed. That keeps `vite build` working in a tree
# where feral-client-v2 is absent, and makes token drift visible as a diff in
# code review rather than as a colour that is only wrong at run time.
#
# If the source is missing this script FAILS. It never silently skips, because
# a skipped sync is exactly the silent drift the step exists to prevent.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DESKTOP_DIR="$(cd "$HERE/.." && pwd)"
REPO_ROOT="$(cd "$DESKTOP_DIR/.." && pwd)"

SRC="$REPO_ROOT/feral-client-v2/src/styles/tokens.css"
DEST="$DESKTOP_DIR/src/tokens.css"
REL_SRC="feral-client-v2/src/styles/tokens.css"

CHECK_ONLY=0
if [ "${1:-}" = "--check" ]; then
  CHECK_ONLY=1
fi

if [ ! -f "$SRC" ]; then
  echo "sync_tokens: source of truth not found at $SRC" >&2
  echo "sync_tokens: the desktop app's colours are generated from $REL_SRC." >&2
  echo "sync_tokens: run this from a full FERAL checkout." >&2
  exit 1
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "/* GENERATED FILE - DO NOT EDIT."
  echo " *"
  echo " * Source of truth: $REL_SRC"
  echo " * Regenerated by:  desktop/scripts/sync_tokens.sh (runs on npm run build)"
  echo " *"
  echo " * Edit the source, not this copy. Any change made here is overwritten by"
  echo " * the next build. The desktop app is a separate Vite package and cannot"
  echo " * import across the package boundary, which is the only reason a copy"
  echo " * exists at all."
  echo " *"
  echo " * Desktop-specific aliases (--bg, --surface, --accent, ...) are NOT here."
  echo " * They live in desktop/index.html, which maps this app's roles onto the"
  echo " * tokens below."
  echo " */"
  cat "$SRC"
} > "$TMP"

if [ "$CHECK_ONLY" = "1" ]; then
  if [ ! -f "$DEST" ] || ! cmp -s "$TMP" "$DEST"; then
    echo "sync_tokens: $DEST is stale against $REL_SRC" >&2
    echo "sync_tokens: run 'npm run sync:tokens' in desktop/ and commit the result." >&2
    exit 1
  fi
  echo "sync_tokens: up to date with $REL_SRC"
  exit 0
fi

if [ -f "$DEST" ] && cmp -s "$TMP" "$DEST"; then
  echo "sync_tokens: already current with $REL_SRC"
  exit 0
fi

cp "$TMP" "$DEST"
echo "sync_tokens: wrote src/tokens.css from $REL_SRC"
