#!/usr/bin/env python3
"""Regenerate feral-core/mypy-baseline.txt, the ratchet the CI typecheck job
compares against.

WHY THIS IS A SCRIPT AND NOT `mypy . > mypy-baseline.txt`
--------------------------------------------------------
Three things make the naive redirect wrong, and all three have already
cost real time in this repo:

1. The baseline file is not pure mypy output. It carries a long hand-written
   header recording why the pydantic plugin is enabled, which call-arg errors
   are known false positives, and what was tried and did not work. A redirect
   destroys that history. This script splices: everything above SENTINEL is
   preserved byte for byte, everything from SENTINEL down is regenerated.

2. The error count is PLATFORM DEPENDENT. The same commit measured 683 when
   the baseline was first written, 751 on macOS in August 2026, and a
   different number again on the ubuntu-latest runner that actually gates
   pull requests. mypy follows into installed dependencies, and which
   dependencies resolve, which ship inline types, and which have platform
   -specific branches all differ between a developer laptop and the runner.
   A baseline generated on macOS is not a smaller-but-safe baseline, it is a
   WRONG baseline that keeps the gate permanently red for reasons no pull
   request author can act on. So writing the real baseline file is refused
   off Linux. See --output for the escape hatch that does not lie.

3. mypy exits non-zero whenever it finds anything, so exit status cannot
   distinguish "found 751 errors" from "crashed on import". A crashed run
   writes little or nothing, and a near-empty baseline silently converts the
   ratchet into "any error at all is a regression". This script requires
   mypy's own summary line before it writes, the same guard the CI job uses.

USAGE
-----
    # what CI does (Linux only), from the repo root:
    python scripts/regen_mypy_baseline.py

    # any platform, to look without writing the gated file:
    .venv/bin/python scripts/regen_mypy_baseline.py --output /tmp/base.txt

The interpreter that runs this must have mypy importable, because the run is
`sys.executable -m mypy`; that is deliberate, so the mypy doing the measuring
is provably the one installed alongside the dependencies being measured.

Configuration comes from feral-core/mypy.ini so this and a bare `mypy .`
cannot disagree.
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import platform
import re
import shutil
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
CORE_DIR = REPO_ROOT / "feral-core"
BASELINE = CORE_DIR / "mypy-baseline.txt"

# The single splice point. Everything ABOVE this line in the existing file is
# hand-maintained prose and is preserved verbatim; this line and everything
# below it is machine-written. One sentinel rather than a begin/end pair
# because the generated part always runs to end of file, and a second marker
# is a second thing that can be lost in a bad merge.
SENTINEL = (
    "# --- everything below this line is generated by "
    "scripts/regen_mypy_baseline.py, do not hand-edit ---"
)

# The exact regex .github/workflows/ci.yml uses to count errors on both sides
# of the comparison. Restated here ON PURPOSE so this script can cross-check
# it against mypy's own total (see _count_errors); if the two ever disagree
# the gate is counting something mypy is not, and that is worth blocking on
# rather than discovering as a mystery delta months later.
CI_ERROR_LINE = re.compile(r"^\S+\.py:\d+: error:")

# mypy always terminates with one of these. Their absence means it did not
# finish, which is the case that must never reach the baseline file.
SUMMARY = re.compile(r"^(Found (\d+) errors? in \d+ files?|Success: no issues found)")


def _run_mypy(purge_cache: bool) -> str:
    """Run `mypy .` in feral-core and return its stdout.

    Non-zero exit is expected and ignored; the summary-line check in
    _split_summary is the real completion test.
    """
    if purge_cache:
        # The baseline header records a false alarm that cost a day: the
        # pydantic plugin was believed to crash mypy 1.20.2, and the real
        # cause was a .mypy_cache written by an earlier run with a different
        # plugin configuration. A baseline is exactly the artifact you must
        # not generate from a stale cache.
        shutil.rmtree(CORE_DIR / ".mypy_cache", ignore_errors=True)

    proc = subprocess.run(
        [sys.executable, "-m", "mypy", "."],
        cwd=CORE_DIR,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.stderr.strip():
        # Never swallowed. mypy writes crashes and plugin load failures here
        # while stdout stays plausible-looking.
        print("mypy stderr:", file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
    return proc.stdout


def _split_summary(stdout: str) -> tuple[list[str], str, int]:
    """Return (error/note lines, summary line, error count mypy reported)."""
    lines = stdout.splitlines()
    for index in range(len(lines) - 1, -1, -1):
        match = SUMMARY.match(lines[index])
        if match:
            reported = int(match.group(2)) if match.group(2) else 0
            return lines[:index], lines[index], reported
    raise SystemExit(
        "mypy produced no summary line, so it crashed or was killed rather "
        "than finishing. Refusing to write a baseline from a partial run: a "
        "short baseline turns the ratchet into 'any error is a regression' "
        "and fires on every pull request.\n"
        "Last 30 lines of output:\n" + "\n".join(stdout.splitlines()[-30:])
    )


def _count_errors(body: list[str]) -> int:
    return sum(1 for line in body if CI_ERROR_LINE.match(line))


def _preserved_header() -> list[str]:
    """Everything above SENTINEL in the current baseline, verbatim."""
    if not BASELINE.exists():
        raise SystemExit(
            f"{BASELINE} does not exist. This script regenerates the machine-"
            "written half of an existing baseline; it will not invent the "
            "hand-written header that explains why the gate is configured the "
            "way it is. Restore the file from git first."
        )
    lines = BASELINE.read_text(encoding="utf-8").splitlines()
    for index, line in enumerate(lines):
        if line.strip() == SENTINEL:
            return lines[:index]
    raise SystemExit(
        f"{BASELINE} has no sentinel line. Expected to find, on a line of its "
        f"own:\n\n    {SENTINEL}\n\n"
        "Without it there is no way to tell the hand-written header from the "
        "generated body, and guessing would silently delete the header. Add "
        "the sentinel immediately below the header and re-run."
    )


def _provenance(summary: str, count: int) -> list[str]:
    """Stamp WHERE the number came from into the file itself.

    The whole failure this script exists to prevent is a baseline measured on
    the wrong platform. Recording the platform in the committed file makes
    that mistake visible in a diff instead of invisible until CI goes red.
    """
    mypy_version = subprocess.run(
        [sys.executable, "-m", "mypy", "--version"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    stamped = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return [
        SENTINEL,
        f"# generated : {stamped}",
        f"# platform  : {platform.system()} {platform.machine()}",
        f"# python    : {platform.python_version()}",
        f"# mypy      : {mypy_version or 'unknown'}",
        f"# errors    : {count}  ({summary})",
        "#",
        "# platform MUST read Linux. Any other value means this baseline was "
        "measured on",
        "# a machine that is not the one gating pull requests, and the gate "
        "will be red",
        "# against it. Regenerate via .github/workflows/mypy-baseline.yml.",
        "#",
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=None,
        help=(
            "write the regenerated baseline here instead of "
            "feral-core/mypy-baseline.txt. Allowed on any platform, because a "
            "file that is not the gate cannot mislead the gate."
        ),
    )
    parser.add_argument(
        "--mypy-output",
        type=pathlib.Path,
        default=None,
        help="also save mypy's raw stdout here, for CI artifact upload.",
    )
    parser.add_argument(
        "--keep-cache",
        action="store_true",
        help="do not delete feral-core/.mypy_cache first. Faster, and unsafe "
        "if the cache predates a change to mypy.ini.",
    )
    args = parser.parse_args()

    destination = args.output or BASELINE
    writing_the_gate = args.output is None

    # The guard this whole exercise is about. Refuse BEFORE spending five
    # minutes in mypy, so the answer is immediate rather than a wasted run.
    if writing_the_gate and platform.system() != "Linux":
        print(
            f"Refusing to write {BASELINE} on {platform.system()}.\n"
            "\n"
            "The mypy error count is platform dependent: the pull-request gate "
            "runs on ubuntu-latest and measures a different number than any "
            "macOS run of the same commit. A baseline written here would keep "
            "that gate permanently red, which is the exact bug this script was "
            "added to end.\n"
            "\n"
            "Regenerate the real one by dispatching "
            ".github/workflows/mypy-baseline.yml (Actions tab, 'Run workflow'); "
            "it runs this same script on the runner and opens a pull request "
            "with the result.\n"
            "\n"
            "To inspect a local number without touching the gate:\n"
            f"    {sys.executable} {__file__} --output /tmp/mypy-baseline.txt",
            file=sys.stderr,
        )
        return 2

    # Read and validate the header BEFORE running mypy, for the same reason
    # the platform guard is above rather than below: a missing sentinel is a
    # failure the script can see in milliseconds, and discovering it after a
    # five-minute cold analysis wastes the run and teaches people to skip the
    # tool.
    header = _preserved_header()

    stdout = _run_mypy(purge_cache=not args.keep_cache)
    if args.mypy_output is not None:
        args.mypy_output.write_text(stdout, encoding="utf-8")

    body, summary, reported = _split_summary(stdout)
    counted = _count_errors(body)
    if counted != reported:
        # Not cosmetic. The gate's number IS `counted`; mypy's headline is
        # `reported`. If they drift apart the gate is measuring something else
        # and its comparison is meaningless in both directions.
        print(
            f"mypy reported {reported} errors but only {counted} lines match "
            f"the regex the CI gate counts with ({CI_ERROR_LINE.pattern}).\n"
            "The gate would therefore ratchet against a number mypy does not "
            "agree with. Fix the regex in .github/workflows/ci.yml and here "
            "together, then re-run. Refusing to write.",
            file=sys.stderr,
        )
        return 1

    content = header + _provenance(summary, counted) + body + [summary, ""]
    destination.write_text("\n".join(content), encoding="utf-8")
    print(f"wrote {destination}: {counted} errors ({summary})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
