// Standalone fixture execution; no real provider/vault/keychain operations.
import Foundation

private final class ChatToolsWire: URLProtocol {
    static let lock = NSLock()
    static var responses: [String: (Int, [String: Any])] = [:]
    static var calls: [(URL, String, [String: Any])] = []
    static var heldPaths = Set<String>()
    static var callbacks: [() -> Void] = []
    override class func canInit(with request: URLRequest) -> Bool { true }
    override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }
    override func startLoading() {
        var bytes = request.httpBody ?? Data()
        if bytes.isEmpty, let stream = request.httpBodyStream { stream.open(); defer { stream.close() }; var buffer = [UInt8](repeating: 0, count: 4096); while stream.hasBytesAvailable { let count = stream.read(&buffer, maxLength: buffer.count); if count <= 0 { break }; bytes.append(buffer, count: count) } }
        let body = (try? JSONSerialization.jsonObject(with: bytes)) as? [String: Any] ?? [:]
        Self.lock.lock(); let path = request.url!.path; Self.calls.append((request.url!, request.httpMethod ?? "GET", body)); let reply = Self.responses[path] ?? (200, [:])
        let respond = { [self] in client?.urlProtocol(self, didReceive: HTTPURLResponse(url: request.url!, statusCode: reply.0, httpVersion: nil, headerFields: ["Content-Type": "application/json"])!, cacheStoragePolicy: .notAllowed); client?.urlProtocol(self, didLoad: try! JSONSerialization.data(withJSONObject: reply.1)); client?.urlProtocolDidFinishLoading(self) }
        let held = Self.heldPaths.contains(path); if held { Self.callbacks.append(respond) }; Self.lock.unlock(); if !held { respond() }
    }
    override func stopLoading() {}
    static func reset(_ values: [String: (Int, [String: Any])]) { lock.lock(); defer { lock.unlock() }; responses = values; calls = []; heldPaths = []; callbacks = [] }
    static func set(_ path: String, _ value: [String: Any], status: Int = 200) { lock.lock(); defer { lock.unlock() }; responses[path] = (status, value) }
    static func count(_ path: String? = nil) -> Int { lock.lock(); defer { lock.unlock() }; return calls.filter { path == nil || $0.0.path == path }.count }
    static func body(_ path: String) -> [String: Any] { lock.lock(); defer { lock.unlock() }; return calls.last(where: { $0.0.path == path && $0.1 != "GET" })?.2 ?? [:] }
    static func passiveOnly() -> Bool { lock.lock(); defer { lock.unlock() }; return calls.allSatisfy { $0.1 == "GET" && !$0.0.path.contains("probe") && (!($0.0.path.hasSuffix("/models")) || URLComponents(url: $0.0, resolvingAgainstBaseURL: false)?.queryItems?.contains(where: { $0.name == "live" && $0.value == "false" }) == true) } }
    static func hold(_ path: String) { lock.lock(); defer { lock.unlock() }; heldPaths.insert(path) }
    static func release() { lock.lock(); let values = callbacks; callbacks = []; heldPaths = []; lock.unlock(); values.forEach { $0() } }
}
private struct ChatToolsAssertion: Error { let message: String }
private func check(_ condition: @autoclosure () -> Bool, _ message: String) throws { if !condition() { throw ChatToolsAssertion(message: message) } }

@main struct NativeChatToolsFeatureTests {
 static let base = URL(string:"http://127.0.0.1:9465")!
 static var plan:[String:Any] { ["session_id":"thread-1","plan_mode":true,"reason":"Read first","plan_count":1,"latest_plan":["title":"Inspect"]] }
 static var entity:[String:Any] { ["id":"thought-1","kind":"thought","owner_session_id":"thread-1","status":"paused","summary":"Half thought","context_json":["text":"Continue fixture"]] }
 static var snapshot:[String:Any] { ["snapshot_id":"snap-1","session_id":"thread-1","label":"Fixture","branch_name":"main","history":[["role":"user","content":"Original","opaque":["keep":true]],["role":"assistant","content":"Reply"]],"working":[["role":"user","text":"Working"]],"created_at":1234] }
 static var fixtures:[String:(Int,[String:Any])] { ["/api/sessions/thread-1/plan_mode":(200,plan),"/api/consciousness/state":(200,["entities":[entity]]),"/api/session/snapshots":(200,["snapshots":[["snapshot_id":"snap-1","session_id":"thread-1","label":"Fixture","branch_name":"main","created_at":1234]]]),"/api/session/snapshots/snap-1":(200,snapshot)] }
 @MainActor static func make(_ url:URL? = base,_ id:String? = "thread-1")->NativeChatToolsModel { let c = URLSessionConfiguration.ephemeral; c.protocolClasses = [ChatToolsWire.self]; return NativeChatToolsModel(baseURL:url,sessionID:id,session:URLSession(configuration:c)) }
 @MainActor static func main() async {
 do {
 ChatToolsWire.reset(fixtures); for m in [make(nil),make(base,nil),make(URL(string:"https://example.com")),make(URL(string:"http://user:secret@127.0.0.1:9465"))] { await m.refresh() }; try check(ChatToolsWire.count()==0,"unsafe/unscoped API dispatched"); print("PASS unavailable/remote/credential and nil session make zero calls")
 ChatToolsWire.reset(fixtures); let p = make(); await p.refresh(); let approval = try p.review("plan_approve"); try check(approval.summary.contains("individual steps") && approval.body["approved"] as? Bool == true && approval.body["enabled"] as? Bool == false,"plan grant semantics"); var off = plan; off["plan_mode"] = false; ChatToolsWire.set("/api/sessions/thread-1/plan_mode",plan); ChatToolsWire.hold("/api/sessions/thread-1/plan_mode"); let task = Task { await p.execute(approval) }; for _ in 0..<100 { if ChatToolsWire.count("/api/sessions/thread-1/plan_mode")>=2 {break}; try await Task.sleep(nanoseconds:10_000_000) }; ChatToolsWire.set("/api/sessions/thread-1/plan_mode",off); ChatToolsWire.release(); _ = await task.value; try check(p.notice?.contains("no task permissions") == true && ChatToolsWire.body("/api/sessions/thread-1/plan_mode")["approved"] as? Bool == true,"plan actual GET check and POST contract"); print("PASS reviewed plan approval leaves mode without granting tasks")
 ChatToolsWire.reset(fixtures); let changed = make(); await changed.refresh(); let r = try changed.review("plan_leave"); var changedPlan = plan; changedPlan["reason"] = "Changed"; ChatToolsWire.set("/api/sessions/thread-1/plan_mode",changedPlan); _ = await changed.execute(r); try check(ChatToolsWire.body("/api/sessions/thread-1/plan_mode").isEmpty && changed.notice==nil,"stale plan mutated"); print("PASS changed plan snapshot blocks mutation")
 ChatToolsWire.reset(fixtures); let s = make(); s.tab = .snapshots; await s.refresh(); await s.inspect("snap-1"); let restore = try s.review("restore",id:"snap-1"); try check(restore.body["session_id"] as? String == "thread-1" && restore.body["as_new_session"] as? Bool == false && restore.summary.contains("Does not undo file edits"),"reviewed restore scope"); ChatToolsWire.set("/api/session/restore",["status":"restored","target_session_id":"thread-1","restored_from_snapshot_id":"snap-1","snapshot":["snapshot_id":"new-snap"]]); let result = await s.execute(restore); try check(result?.session=="thread-1" && (result?.history.first?["opaque"] as? [String:Any])?["keep"] as? Bool == true,"opaque restored history lost"); try check(ChatToolsWire.count("/api/conversations/save")==0,"runtime restore implicitly saved UI thread"); try check(s.canApply(result!),"fresh runtime result not applicable"); let extraReview = try s.review("snapshot"); s.tab = .plan; await s.refresh(); let planDuringApply = try s.review("plan_enter"); s.tab = .thoughts; await s.refresh(); let thoughtDuringApply = try s.review("resume",id:"thought-1"); s.tab = .snapshots; try check(s.beginApply(result!),"active apply lock not acquired"); try check(s.canApply(result!),"apply lock invalidated its own result"); var applyBlocked = false; do { _ = try s.review("snapshot") } catch { applyBlocked = true }; _ = await s.execute(extraReview); _ = await s.execute(planDuringApply); _ = await s.execute(thoughtDuringApply); try check(applyBlocked && ChatToolsWire.count("/api/session/snapshot")==0 && ChatToolsWire.body("/api/sessions/thread-1/plan_mode").isEmpty && ChatToolsWire.count("/api/consciousness/resume")==0,"apply lock allowed unrelated mutation"); s.endApply(result!); try check(!s.applyingHistory && s.canApply(result!),"apply unlock invalidated active review"); s.setChatBusy(true); try check(!s.canApply(result!),"busy host accepted apply result"); s.setChatBusy(false); try check(!s.canApply(result!),"prior apply result survived busy transition"); s.configure(baseURL:nil,sessionID:nil); try check(!s.canApply(result!),"stale runtime result applicable to new agent"); print("PASS exact runtime restore, opaque history, separate apply lock with zero unrelated POST and preserved review")
 ChatToolsWire.reset(fixtures); let drift = make(); drift.tab = .snapshots; await drift.refresh(); await drift.inspect("snap-1"); let branch = try { () -> NativeChatToolReview in drift.branchName="experiment"; return try drift.review("branch",id:"snap-1") }(); var moved = snapshot; moved["label"] = "Changed"; ChatToolsWire.set("/api/session/snapshots/snap-1",moved); _ = await drift.execute(branch); try check(ChatToolsWire.count("/api/session/branch")==0,"changed snapshot branched"); print("PASS refreshed inspected snapshot required before branch")
 ChatToolsWire.reset(fixtures); let thought = make(); thought.tab = .thoughts; await thought.refresh(); let resume = try thought.review("resume",id:"thought-1"); ChatToolsWire.set("/api/consciousness/resume",["ok":true,"rehydrated":["kind":"thought","method":"status_only"]]); _ = await thought.execute(resume); try check(thought.notice?.contains("status_only") == true && thought.notice?.contains("not proof") == true,"status-only resume called execution"); print("PASS resume acknowledgement never fabricates execution")
 ChatToolsWire.reset(fixtures); let scoped = make(); scoped.tab = .thoughts; var other = entity; other["owner_session_id"] = "another-thread"; ChatToolsWire.set("/api/consciousness/state",["entities":[other]]); await scoped.refresh(); try check(scoped.error != nil && !scoped.fresh.contains(.thoughts),"foreign session entities accepted"); print("PASS session-owned entities strictly validated")
 ChatToolsWire.reset(fixtures); let stale = make(); await stale.refresh(); let old = try stale.review("plan_enter"); stale.configure(baseURL:base,sessionID:"new-thread"); _ = await stale.execute(old); try check(ChatToolsWire.body("/api/sessions/thread-1/plan_mode").isEmpty,"stale session review dispatched"); ChatToolsWire.reset(fixtures); ChatToolsWire.hold("/api/sessions/thread-1/plan_mode"); let delayed = make(); let loading = Task { await delayed.refresh() }; for _ in 0..<100 {if ChatToolsWire.count()>0 {break}; try await Task.sleep(nanoseconds:10_000_000)}; delayed.configure(baseURL:nil,sessionID:nil); ChatToolsWire.release(); await loading.value; try check(delayed.plan.isEmpty && delayed.fresh.isEmpty && delayed.error==nil,"old backend response restored state"); print("PASS stale reviewed session and delayed backend responses are discarded")
 ChatToolsWire.reset(fixtures); for operation in ["plan_enter","plan_leave","plan_approve","snapshot","branch","restore","restore_new","resume","pause","abandon"] {
  let gated = make(); gated.tab = operation.hasPrefix("plan_") ? .plan : ["resume","pause","abandon"].contains(operation) ? .thoughts : .snapshots; await gated.refresh(); if ["branch","restore","restore_new"].contains(operation) { await gated.inspect("snap-1"); gated.branchName="fixture-branch" }; let id = ["resume","pause","abandon"].contains(operation) ? "thought-1" : "snap-1"; let reviewed = try gated.review(operation,id:id); gated.setChatBusy(true); var rejected = false; do { _ = try gated.review(operation,id:id) } catch { rejected = true }; try check(rejected,"busy host allowed review"); _ = await gated.execute(reviewed); gated.setChatBusy(false); _ = await gated.execute(reviewed); try check(gated.notice==nil,"busy-transition review remained valid")
 }; try check(ChatToolsWire.calls.allSatisfy{$0.1=="GET"},"host-busy mutation dispatched"); print("PASS every mutation blocked while busy and prior reviews invalid after idle returns")
 ChatToolsWire.reset(fixtures); let awaiting = make(); await awaiting.refresh(); let waitingReview = try awaiting.review("plan_leave"); ChatToolsWire.hold("/api/sessions/thread-1/plan_mode"); let changing = Task { await awaiting.execute(waitingReview) }; for _ in 0..<100 { if ChatToolsWire.count("/api/sessions/thread-1/plan_mode")>=2 {break}; try await Task.sleep(nanoseconds:10_000_000) }; awaiting.setChatBusy(true); ChatToolsWire.release(); _ = await changing.value; try check(ChatToolsWire.body("/api/sessions/thread-1/plan_mode").isEmpty,"busy change during preflight dispatched POST"); awaiting.tab = .snapshots; await awaiting.refresh(); await awaiting.inspect("snap-1"); try check(awaiting.inspected?["snapshot_id"] as? String=="snap-1","host busy prevented passive inspect"); print("PASS busy transition after awaited preflight blocks dispatch; passive inspect remains available")
 ChatToolsWire.reset(fixtures); let managed = make(); managed.tab = .snapshots; await managed.refresh(); await managed.inspect("snap-1"); managed.branchName = "fixture"; let staleContext = try managed.review("snapshot"); managed.setContextPolicy(mutationsAllowed:true,blockedOperations:["snapshot","branch","restore"])
 for operation in ["snapshot","branch","restore","restore_new"] { var rejected = false; do { _ = try managed.review(operation,id:"snap-1") } catch { rejected = true }; try check(rejected,"managed context permitted unsupported snapshot action") }
 _ = await managed.execute(staleContext); try check(ChatToolsWire.passiveOnly(),"mode transition allowed stale snapshot POST")
 managed.setContextPolicy(mutationsAllowed:false,blockedOperations:[]); managed.tab = .plan; await managed.refresh(); var unreadyRejected = false; do { _ = try managed.review("plan_enter") } catch { unreadyRejected = true }; try check(unreadyRejected,"unready context allowed mutation")
 managed.tab = .snapshots; await managed.refresh(); await managed.inspect("snap-1"); try check(managed.inspected != nil && ChatToolsWire.passiveOnly(),"unready context hid read-only inspection")
 managed.setContextPolicy(mutationsAllowed:true,blockedOperations:[]); managed.tab = .plan; await managed.refresh(); _ = try managed.review("plan_enter"); print("PASS saved-context restrictions invalidate reviewed changes without blocking passive inspection or standard chats")
 print("11 Chat tools fixture groups passed; mocked HTTP only, no production session actions or native GUI verification.")
 } catch { print("FAIL \(error)"); exit(1) }
 }
}
